pagopa/io-services-metadata

services.yml

Replace 'funzionlità' with 'funzionalità'

[162421352] Fix wrong description service

---

src/update_services.ts

This PR adds a warning in update_services task if some services have no email and phone in attrs

Warning no email and phone in service attrs

---

definitions.yml
idps/idps.json

This PR adds IDPS text data type definition
A idps.json with some dummy data

Add IDPs text type definition

---

README.md
municipalities/A/5/A559.json
municipalities/D/0/D005.json
municipalities/D/5/D583.json
municipalities/E/1/E151.json
municipalities/H/5/H579.json
municipalities/Z/1/Z118.json

Added some missing municipalities

Add missing municipalities

---

definitions.yml

Add `support_url` as optional string field in `Service` model

[#173735244] Add support url

---

status/backend.json

- Added URL to "Wallet" message

status update

---

src/checkBackendStatus.ts
status/backend.json

Update backend status 6

---

status/backend.json

This PR shows the "normal" status info to better display the FAQ about avg time to get valid transactions.

Status Update in Cashback Detail page

---

bonus/bonus_available.json
bonus/bonus_available_v1.json
bonus/bonus_available_v2.json
bonus/vacanze/bonuses_available.json

Replace bonus url logo

---

status/backend.json

New year status message

---

status/backend.json

CIE under maintenance status message published

---

status/cobadgeServices.json

Enable SIA for co-badge search

---

status/cobadgeServices.json

This pr disables SIA as service.

Change SIA to disabled

---

status/cobadgeServices.json

This pr disables SIA for co-badge search

Disable SIA for co-badge search

---

contextualhelp/data.json

- Added content for co-badge screens
- Changed content for PagoBANCOMAT detail screen
- Added content for debit/credit card screen
- Added routes

177035772 cobadge faq

---

status/backend.json

This PR enables Payments unavailable banner on wallet and messages sections

Payments unavailable status banner

---

status/cobadgeServices.json

This pr enables SIA and ICCREA for the co-badge search

Enable SIA and ICCREA for co-badge search

---

bonus/specs/bpd/pm/walletv2.json

This pr upates the definition for `CardInfo`, in order to support the new type `PRV`

[#177186994] Update CardInfo definition

---

bonus/specs/bpd/pm/walletv2.json

This pr updates the privative card specification

[#177142050] Update privative card specification

---

status/privativeServices.json

[#177326588] Update privativeServices.json

---

contextualhelp/data.json

Typo fixes in contextual help

---

bonus/specs/bpd/winning_transactions_v2.json

This pr patches the winning_transactions_v2 specs.

[#177543882] Patch winning-transactions v2 spec

---

bonus/specs/bpd/winning_transactions_v2.json

- change required for prev & next cursor
- remove patch description

Update winning-transactions-v2 API specs

---

README.md

Test merge master

---

status/cobadgeServices.json

add CREDEM and EUROMOBILIARE cobadge service

[BSP-91] new psps managed by SIA

---

status/backend.json

This PR adds a warning banner about issues with in-app payments

[IA-37] Banner in Wallet

---

contextualhelp/data.json

This PR Adds a new FAQ about issues when updating on Android

[IA-46] New FAQ

---

contextualhelp/data.json

[IA-57] Typo fix

---

status/backend.json

- Remove banner from Wallet
- Add banner in Cashback page

[IAC-92] Banner update

---

status/backend.json

Aggiornato il testo del banner del Cashback, aggiunto URL

[IAC-94] Banner update

---

src/@types/backendStatus.ts
status/backend.json

This pr adds the remote config for bpd enroll after add payment method.

[IAC-97] Remote config for bpd enroll after add payment method

---

definitions.yml
status/backend.json

This pr adds the new bpd `program_active` remote feature flag.

[IAC-107] Add program_active feature flag

---

status/backend.json

This PR adds a banner in the language selection screen

[IA-151] Banner in Favourite Language screen

---

status/backend.json

[IAC-116] Banner about Cashback mantainance

---

status/backend.json

This reverts commit cb04c6a4599c529a5660beb67072080097587155.

Revert "[IAC-116] Banner about Cashback mantainance (#480)"

---

status/backend.json

This reverts commit d79c1571bbe87af4fcf88ea5c3d8625fd6785eaa.

Revert "[IAC-116] Banner about Cashback mantainance #482"

---

status/backend.json

This PR turns off the current Banner in Wallet section

[IA-438] Banner off

---

status/backend.json

New warning about issues with pagoPA platform

[IA-526] Banner in Wallet Section

---

status/backend.json

Reverts pagopa/io-services-metadata#520

Revert "[IA-526] Banner in Wallet Section"

---

definitions.yml

This PR fix the zendesk ff definition making it required

[ASZ-103] Make zendesk ff required

---

status/backend.json

[IA-547] New status banner

---

status/backend.json

This PR disables banners turned on with #523

[IA-548] Revert banners

---

definitions.yml
status/backend.json

This PR modify the definition and the value of the zendesk remote FF.
| Before  | After |
| ------------- | ------------- |
| boolean  | "none" or "zendesk" or "instabug" or "web"  |

[IA-549] Modify zendesk remote ff

---

definitions.yml
package.json
status/backend.json

This PR updates the specs and the relative payload data to enable the paypal banner

[IA-570] Add paypal banner

---

assistanceTools/zendesk.json

This PR align the categories with those created in the Zendesk portal.
It updates the existing values and ids and add the categories that wasn't not in the file.

Add all the categories created in Zendesk

---

assistanceTools/zendesk.json

This PR align the category and the sub-categories id with those created in the Zendesk portal.

Fix category and subcategories id

---

status/backend.json

This PR set Zendesk as the assistance tool

Activate Zendesk

---

assistanceTools/zendesk.json

various changes to the categories and sub-categories copy

[IA-516] categories and sub-categories copy

---

status/backend.json

This PR set instabug as assistanceTool waiting the end of the rollout

set instabug as assistanceTool

---

status/backend.json

https://user-images.githubusercontent.com/822471/147820451-722c5d85-0ecd-4bbd-97d9-facf2594a88c.mov

[IAC-106,IAC-124] Cashback off

---

status/backend.json

Added URL to Cashback landing page

Added URL to Cashback Banner

---

definitions.yml
package.json
src/checks/checkAbi.ts
src/checks/checkBackendStatus.ts
src/checks/checkBonusAvailable.ts
src/checks/checkCoBadge.ts
src/checks/checkContextualHelpData.ts
src/checks/checkIdpsData.ts
src/checks/checkPrivative.ts
src/checks/checkZendesk.ts
status/backend.json
yarn.lock

This PR updates the `Config` model to add the `paypal` section
It also replaces the current check of duplicated keys in a JSON file with a library that does it in more accurate way
https://github.com/jackyjieliu/json-dup-key-validator

[IA-613] Add Paypal remote config

---

definitions.yml
package.json
status/backend.json

This PR introduces CGN remote feature flag and configuration

[IOACGN-19] Introduces new CGN remote feature flag

---

definitions.yml
status/backend.json

This PR adds the section status information for CGN status messages

Supports remote status for CGN messages

---

contextualhelp/data.json

Insertion of a FAQ concerning international cards and modification of an existing text.

[IA-529] FAQ contextual help international cards

---

definitions.yml
status/backend.json

This PR adds the remote feature flag for the opt-in of the payment methods.

[IAC-132] Opt-in payment methods remote feature flag

---

status/backend.json

This PR enables remote feature flag for CGN for internal beta

enables CGN remote FF

---

contextualhelp/data.json

FAQ for Certificazione Verde updated and Certificazione di esenzione added.

[IA-645] FAQ: copy update Certificato Verde - Certificato di esenzione

---

src/checks/checkAbi.ts
src/checks/checkBackendStatus.ts
src/checks/checkBonusAvailable.ts
src/checks/checkContextualHelpData.ts
src/checks/checkIdpsData.ts
src/checks/checkPrivative.ts
src/checks/checkZendesk.ts

This pr refactorizes all the json sanity check in order to use the common `basicJsonFileValidator` chained with the specific custom check for each domain in a functional way.
PS: All the checks have been updated except `src/checks/checkCoBadge.ts`that requires more work.

[IAI-119] Refactor json sanity check reusing shared code

---

.circleci/PULL_REQUEST_TEMPLATE.md

This pr adds a pull request template

chore: Add pull request template

---

status/versionInfo.json

This pr updates the min app version to `1.32.0`

chore: Update min app version to `1.32.0`

---

bonus/bonus_available_v2.json

Updates CGN bonus informations to remove Guide CTA on app

Remove guide url from CGN bonus information

---

contextualhelp/data.json

New faq added for Certificazione di esenzione.

[IA-665] New FAQ added

---

status/backend.json

This PR disables CGN remote FF

[IOACGN-56] Disables CGN remote FF

---

status/backend.json

[IA-685] Scheduled Maintenance banner

---

definitions.yml
status/backend.json

This PR adds the definitions and the value for the config of the donations flow.
Note that the URL and the EN text are not definitive.

[IA-696] Donations config

---

html/donate.html

This page was already reviewed and tested in https://github.com/pagopa/io-dev-api-server/pull/145

[IA-789] Include the donations page

---

html/donate.html

Integrate the changes made in: https://github.com/pagopa/io-dev-api-server/pull/147

[IA-719] Fix various `donate.html` issues

---

html/donate.html

The donations can be made with PayPal too. These copy changes reflect this.

[IA-737] copy update

---

status/backend.json

Since tests are over, switch off the uaDonation FF

UAdonation OFF

---

definitions.yml
status/backend.json

This PR introduces FIMS remote feature flag

[IAFIMS-2] Introduces fims remote feature flag

---

html/donate.html

This PR is going to sync the changes made on https://github.com/pagopa/io-dev-api-server/pull/153.

[IA-751] Sync submit button font change on the donations page

---

contextualhelp/data.json

Added FAQ (both in Italian and English) about the donations service.
**merge only after the service is up and running**

[IA-745] Donation FAQ added

---

status/backend.json
status/docs/versionInfo.md

This PR adds the link to learn more about the disruption

Banner update

---

contextualhelp/data.json

added a sentence to a FAQ dedicated to donations, as per the legal team request

[IA-756] copy changes

---

definitions.yml
status/backend.json

This PR add the definition and the value of the `cdc` (carta della cultura) feature flag

[AP-17] Carta della cultura feature flag

---

contextualhelp/data.json

[IA-760] Messages: FAQ update

---

status/backend.json

This PR adds the fims dev domain to test the alpha version of the APK

[FIMS-37] FIMS dev domain for test purpose

---

contextualhelp/data.json

Now that payments with AMEX also have no commissions, I have updated the copy of the FAQs

[IA-828] payment network updated

---

contextualhelp/data.json

Added an external link which redirects the users who are having trouble adding a card to the FAQs dedicated to the 3DS service

[IA-808]nadded a link

---

status/backend.json

- Paypal set as false
- Warning Banner in wallet section

[IA-862] Update backend.json

---

contextualhelp/data.json

[IA-852] Copy FAQ BANCOMAT Pay

---

status/backend.json

Banner to temporarily disable PayPal services

Paytipper Banner

---

status/backend.json

- Paypal set as false
- Banner in Wallet

[IAI-205] Paypal scheduled maintenance banner

---

status/backend.json

- Disable PayPal services
- Show Banner in Wallet screen
**Please follow the instructions in the attached Jira ticket**

[IA-899] PayPal Scheduled Maintenance

---

contextualhelp/data.json

As of the next app version, only those who donate with an Android device will receive a receipt.
The related FAQ has been amended, both in Italian and English. 
Merge it only after the new iOS version is released.

[IA-885] Donation FAQ amendments

---

assistanceTools/zendesk.json

Here are the 3 new subcategories:
- Vorrei più informazioni su come richiedere e utilizzare la Carta / I need more info on how to request or use the Card
- Ho un problema con un'agevolazione specifica / I have an issue with a specific discount
- Ho un altro problema / I have a different issue

Add CGN subcategories for Zendesk tickets

---

contextualhelp/data.json

Added the contextual help of the route "PN_ROUTES_MESSAGE_DETAILS"

[IIP-92] FAQ of the route "PN_ROUTES_MESSAGE_DETAILS"

---

status/backend.json

- Disable PayPal services
- Show Warning Banner in Wallet
**This PR needs to be merged on Jul 27th at 20:25 CEST. It needs to be reverted at 22:40 CEST**

[IA-919] Disable PayPal and Show Banner

---

contextualhelp/data.json

@AliceAzzolini added the final FAQs: Profile and Onboarding

[IA-884] New FAQs

---

contextualhelp/data.json

Amended typo in a route + added the attribute "faqs": [] in the routes "PROFILE_PREFERENCES_HOME" + "PROFILE_PRIVACY" not to show old, non-remotized FAQs

[IA-923] Typo rotta "AUTHENTICATION_IPD_SELECTION"

---

contextualhelp/data.json

Added route AUTHENTICATION_IDP_LOGIN, added FAQs to the routes "PROFILE_PRIVACY" and "PROFILE_PREFERENCES_HOME"

[IA-925] copy changes

---

contextualhelp/data.json

Added the FAQs to the route "PN_ROUTES_MESSAGE_ATTACHMENT".
Also added again the FAQs to the route "PN_ROUTES_MESSAGE_DETAILS", which were deleted by accident in a previous PR.

[IIP-94] Added the attachments' FAQs

---

status/backend.json

This PR updates the landing URL of the PN timeline CTA.

Update PN frontend URL

---

status/backend.json

This PR adds a banner in the Wallet section, informing users PayPal will be under maintenance for 2 hours.
⚠️ **This PR needs to be merged at 20:00 on 21/09/2022**

[IAI-243] Enable Banner in Wallet Section

---

status/backend.json

This PR reverts a banner in the Wallet section, informing users PayPal will be under maintenance for 2 hours.
⚠️ This PR needs to be merged once maintenance will be finished

Revert: [IAI-243] Enable Banner in Wallet Section

---

status/backend.json

This PR enables the banner in Wallet section as per https://status.pagopa.gov.it/incidents/dtgh8xdrrdxh.
**It needs to be merged today at 8PM**

[IAI-248] Scheduled maintenance banner

---

definitions.yml
status/backend.json

This PR integrates the new FF for PM optin request in app, a new release will be tagged once this PR will be merged

[IOAPPPEB-3] Handles the new FF for Payment Methods opt-in

---

contextualhelp/data.json

Added Italian and English FAQs for the "PROFILE_PREFERENCES_NOTIFICATIONS" route

[IOAPPCOM-11] Added opt-in FAQs

---

status/backend.json

Disable banner in wallet section

---

html/donate.html

This PR adds a caption with end date in the main flow of the donation service.

[IOAPPCIT-29] Update donate.html

---

status/versionInfo.json

This PR will update the min app supported version

Update min app version

---

status/backend.json

This PR disables the donations banner in app

[IOAPPCOM-34] Disables Donations banner

---

html/donate.html

Updates the donate html file to disable the donations flow

updates the donate html file

---

status/backend.json

This PR enables the lollipop feature flag.

[LLK-10] Enable lollipop feature

---

status/backend.json

Banner in wallet section to inform about pagoPA disruption

[banner] Update backend.json

---

status/backend.json

Warning banner in:
- login
- ingress
- messages

Warning banner

---

status/backend.json

Turn banner off

---

assistanceTools/zendesk.json

Add 'Firma con IO' category in Zendesk

Add 'Firma con IO' category in Zendesk

---

contextualhelp/data.json

Added Italian FAQs for Firma con IO

[SFEQS-1500] faq update

---

contextualhelp/data.json

[SFEQS-1623] FAQ update

---

sign/io-sign.js

this change updates `io-sign.js` library to its latest version

fix: [SFEQS-1697] Update io-sign.js to the latest version

---

status/backend.json

This PR add a status banner on login page due to a CIE login issue.

Status banner on login page: CIE service is down

---

contextualhelp/data.json

Firma con IO FAQ addition and update

[SFEQS-1667] FAQ addition and update

---

status/backend.json

This PR removes status banner due to CIE login issues.

Revert "Status banner on login page: CIE service is down"

---

package.json

Bump version to 1.0.25

---

contextualhelp/data.json

[IA-955] added some FAQs for CGN

---

status/backend.json

This PR adds a status banner on login page due to a CIE login issue.

Status banner on login page: login with CIE has issues.

---

status/backend.json

This PR enables FIMS in production and updates the provider URL

[IOCOM-334] Enables FIMS in production

---

status/backend.json

Reverts pagopa/io-services-metadata#723

Revert "Status banner on login page: login with CIE has issues."

---

status/backend.json
status/versionInfo.json

This PR adds the FF that enables the FL feature.

[IOPID-417] Enable fast login

---

contextualhelp/data.json

This PR removes FAQ related to privative cards (supermarkets)

chore: [IOBP-153] privative cards FAQ deletion

---

contextualhelp/data.json

- Removed PagoBANCOMAT FAQs
- Fixed typo in BANCOMAT Pay FAQ

[IOBP-154] Remove PagoBANCOMAT FAQs

---

definitions.yml
package.json
status/backend.json

This PR adds `min_app_version` field to `pn`.

[IOCOM-527] Add `min_app_version` to `pn`

---

definitions.yml
package.json

This PR adds the specification for the opt-in fast login feature
Its properties are marked as not required.
If not present, the feature will be disabled.

[Iopid-951] Added opt-in fast login specs

---

contextualhelp/data.json

This PR adds the FAQ for PN's multiple payments.
- Added an FAQ to the bottom of PN_ROUTES_MESSAGE_DETAILS route

[IOCOM-521] FAQ for PN's multiple payments

---

contextualhelp/data.json
status/backend.json

This PR sets the minimum app version for PN to 2.46.0.3

[IOCOM-573] PN min app version

---

.github/workflows/publish_cdn.yml
azure-pipelines.yml

[IOPID-1207] Add github pipeline

---

.github/workflows/publish_cdn.yml
.identity/env/prod/terraform.tfvars

Replace single quotes with double ones and give properly permission to the managed identity

[EC-40] Fix identity permissions

---

contextualhelp/data.json

This PR adds a FAQ regarding messages with remote content
- renamed `MESSAGE_DETAIL_PAGINATED` to `MESSAGE_DETAIL`
- added an FAQ to the bottom of `MESSAGE_DETAIL`

[IOCOM-741] FAQ for messages with remote content 

---

.github/workflows/publish_cdn.yml

Fix pipeline syntax

---

.github/workflows/publish_cdn.yml

Get CDN name from env var rather than hardcoded value

Use env vars rather than hardcoded value

---

status/backend.json

This PR enables the Email Uniqueness Validation FF

[IOPID-1182] chore: enable email uniqueness FF

---

contextualhelp/data.json

[IOBP-79] Cashback faq removal

---

definitions.yml
package.json
status/backend.json

This PR add `TosConfig` to `BackenStatus.Config` and a first payload data.

[IOPID-1371] Add `TosConfig` to `BackenStatus.Config`

---

contextualhelp/data.json

I think the ONBOARDING_FINGERPRINT and ONBOARDING_PIN part is not up to date after the recent release of "accesso rapido"....

🇩🇪 language

---

contextualhelp/data.json

Added a new faq to suggest resolution with a problem with Android.

[IOPID-1646] New faq added

---

spid/idps/list.json

Align list.json with list2.json in order to delete list2.json after next mandatory version increase.

[IOPID-1502] Alignment of the list.json with the list2.json

---

bonus/bonus_available.json
bonus/bonus_available_v1.json
bonus/bonus_available_v2.json
bonus/vacanze/bonuses_available.json
status/backend.json

Change CDN urls from assets.cdn.io.italia.it to assets.cdn.io.pagopa.it for all occurrence
Verify that each link works identically to the as-is

[IOPID-1739] change CDN urls 

---

spid/idps/list.json
spid/idps/list2.json

Change IdPs commercial name 
| Old | New | 
| - | - |
| <video src="https://github.com/pagopa/io-app/assets/83651704/5737e119-2129-4175-8b92-2d3dc342a3e8" /> | <video src="https://github.com/pagopa/io-app-design-system/assets/83651704/3d68d8cd-c6f6-40b5-82d8-6452d5887fe3" /> |
Run the app ([io-app](https://github.com/pagopa/io-app)) and do the login flow using spid

[IOPID-1809] Change IdPs commercial name 

---

status/backend.json

Removed banner from language selection screen

Removed banner from language selection screen

---

contextualhelp/data.json

Updated FAQ for the services section in both Italian and English

[IOPAE-946] Services FAQ update

---

status/backend.json

This PR updates the FIMS domain.
- FIMS domain updated
Static checks should pass.

[IOCOM-1555] Update FIMS domain

---

status/backend.json

This PR needs to be merged on Jun 14th

Banner on legacy wallet page

---

status/backend.json

see title
- Feature A
- Feature B

Addition of fims historyEnabled feature flag

---

status/backend.json

Disable payments section

---

status/backend.json

This PR updates `min_app_version` for `newPaymentSection` to `3.0.0.0`

chore: change `min_app_version` to `3.0.0.0` for `newPaymentSection`

---

status/backend.json

This PR enables the new payment section FF to apps with min version `2.65.0.0`
- Set min app version to `2.65.0.0`

chore: enable new payments section FF

---

definitions.yml
package.json
status/backend.json

This PR adds it-wallet remote config to enable disable it-wallet feature
- Update services definitions
- Update data.json
- Update version number in package.json

feat(it-wallet): [SIW-1357] Add `itw` remote config

---

status/backend.json

this banner updates the content to the legacy version inviting users to update the app to the lasest version

Legacy banner update

---

contextualhelp/data.json

removed "dal 25 luglio" references

Update PayPal FAQs

---

status/backend.json

This PR enable remote FF for ITW feature. Also updates min_app_version to the latest io-app version.
- Update ITW remote config

chore: enable `itw` remote feature flag and set `min_app_version` to `2.67.0.2` 

---

contextualhelp/data.json

[IOBP-792] FAQ update and fix

---

status/backend.json

chore: banner for `namirialid` down

---

status/backend.json

Reverts pagopa/io-services-metadata#819

Revert "chore: banner for `namirialid` down"

---

definitions.yml
status/backend.json

This PR adds new feature flags for FIMS.
- min_app_version for authentication flow
- min_app_version for history screen
- set false for legacy property
Static checks should not fail.

[IOCOM-1641] New structure for FIMS metadata

---

definitions.yml
package.json
status/backend.json

Added `cie_id` Feature Flag
- Added `cie_id` Feature Flag
- Added `cie_id` FF definition

feat(IOPID-2189): add `cie_id` FF definition

---

status/backend.json

this PR activates the remote feature flag which is used to activate the session refresh when the user returns to foreground

[IOPID-2198] activate session refresh remote feature flag

---

contextualhelp/data.json

Updated FAQ of the payment receipt screen. 
Corrected the route PAYMENT_TRANSACTION_BIZ_EVENTS_DETAILS

[IOBP-849] 

---

contextualhelp/data.json

Updated and modified the FAQ in the settings section, both in Italian and English

[IOPID_2184]

---

contextualhelp/data.json

- Correct typo in the contextual help of the route PAYMENT_ONBOARDING_SELECT_METHOD
- Fixed the FAQ of the route PAYMENT_METHOD_DETAILS_SCREEN

[IOBP-846] Payment FAQ update

---

contextualhelp/data.json

(Broken link) FAQ update

---

definitions.yml

This PR sets `uaDonations` as optional in order to allow the removal of the entire feature in app IO.
N/A
N/A

chore: [IOAPPX-386] Make uaDonations optional

---

status/backend.json

This PR updates the app ToS version to 4.92.
N/A
N/A

chore: [SIW-1722] Update ToS version to 4.92

---

contextualhelp/data.json

[SIW-1776] Update FAQ Wallet

---

assistanceTools/zendesk.json

🇩🇪 strings "documenti su io"

---

contextualhelp/data.json

[SIW-1781] FAQ update

---

contextualhelp/data.json

This PR adds a new FAQ in the payment flow

chore: [IOBP-932] New FAQ

---

contextualhelp/data.json

This pull request include the addition of `PAYMENT_NOTICE_SUMMARY` FAQ sections 
-  Added a new FAQ section for the `PAYMENT_NOTICE_SUMMARY` route, including explanations for discrepancies in payment amounts and due dates.
- Corrected the formatting of the existing FAQ entry

chore: [IOBP-717] Payments checkout summary route

---

contextualhelp/data.json

This PR adds the missing FAQ that must be shown on the select payment method screen.

chore: [IOBP-932] Add missing FAQ after regression into select payment method screen

---

contextualhelp/data.json

Added new FAQ and modified some of the previous ones.

[SIW-1821] Wallet FAQ update

---

definitions.yml
package.json
status/backend.json

This PR extends the definitions for IT Wallet `sections` and `config` in order to support remote content.
- Added the following optional sections:
- `itw_discovery_tos`
- `itw_identification`
- `itw_credential_onboarding`
- Added additional config entries
- Bumped version to `1.0.46`

chore(IT Wallet): [SIW-1861] Update definitions and backend status

---

definitions.yml
package.json

Since the login using cieid as idp has been added, we have also added this idp in the definitions of this repository

[IOPID-2137] Add cieid as idp 

---

definitions.yml

This pull request add a reference for German language (`de`) to the `ContextualHelpData` definition

feat: [IOBP-961] add de type for ContextualHelpData

---

package.json

This pull request includes a small change to the `package.json` file. The change updates the version number from `1.0.48` to `1.0.49` to reflect the latest modifications

chore: adjust package version

---

status/backend.json

chore: [SIW-1891] Add status message for TEAM

---

status/backend.json

The version of the app that allows remote FF activation of `cie_id` feature has been changed

[IOPID-2508] activate cie_id remote FF

---

status/backend.json

chore: update TEAM stats message

---

status/backend.json

[SIW-1892] Re-enable Tessera Sanitaria - TEAM

---

status/backend.json

Disable banner for Tessera Sanitaria

[SIW-1893] Disable banner for Tessera Sanitaria

---

contextualhelp/data.json

Missing space in FAQ

---

contextualhelp/data.json

Added new FAQ for the implementation of login with CieID in authentication routes.

[IOPID-2509] Add and update FAQ 

---

contextualhelp/data.json

Now links should appear as proper ones

Fixed wrong markdown syntax

---

contextualhelp/data.json

Made some changes for the Wallet FAQ.

[SIW-1894] FAQ Wallet update

---

status/backend.json

Enables the status message in `ITW_CARD_ONBOARDING` screen.

Activate status message in the credential selection screen

---

contextualhelp/data.json

Two FAQ deleted in WALLET_HOME

FAQ Update 

---

status/backend.json

Disable `ITW_CARD_ONBOARDING` status message.

chore(IT Wallet): Disable `ITW_CARD_ONBOARDING` status message

---

assistanceTools/payments/zendeskOutcomeMapping.json
assistanceTools/zendesk.json

> [!NOTE]
> You can test it with this [PR](https://github.com/pagopa/io-dev-api-server/pull/448)
This pull request includes changes to the `assistanceTools/payments/zendeskOutcomeMapping.json` and `assistanceTools/zendesk.json` files to update the mapping and categorization of payment-related issues in the Zendesk system.

feat: [IOBP-1045] Add zendesk receipt subcategories

---

definitions.yml

- add `deferred_issuance_mdl` object in `ItwConfig` to handle the content displayed when there is a deferred issuance of MDL

[SIW-1901] Deferred issuance for MDL

---

package.json

This PR bumps the package version to `1.0.51`

Bump package version to `1.0.51`

---

status/backend.json

This PR enabled the IT Wallet feedback banner
- Set `itw.feedback_banner_visible` to `true`

Enable IT Wallet feedback banner

---

contextualhelp/data.json

Added new faq for the PROFILE_FISCAL_CODE route

[IOPID-2558]

---

contextualhelp/data.json

This pull request includes updates to the `contextualhelp/data.json` file, adding new contextual help entries for various payment receipt screens. The changes introduce new routes and corresponding FAQ sections. However, `BIZ_EVENT` objects must remain for legacy compatibility at this time.
- Added a new entry for the `PAYMENT_RECEIPT_LIST_SCREEN`
- Added a new entry for the `PAYMENT_RECEIPT_DETAILS` 
- Added a new entry for the `PAYMENT_RECEIPT_PREVIEW_SCREEN`

refactor: [IOBP-1050] Add new payment receipt objects

---

assistanceTools/payments/zendeskOutcomeMapping.json
assistanceTools/zendesk.json

Replace old payment tags
- Replaced "pagamenti_pagopa" with "pagamenti_pagopa_errore"
- Replaced "metodo_di_pagamento" with "pagamenti_pagopa_aggiunta_metodo"

Replace old payment tags

---

assistanceTools/zendesk.json

Replace tag `pagamenti_ pagopa_info_stato` with `pagamenti_pagopa_info_stato`

Fix a typo in "Vorrei informazioni sullo stato di un pagamento"

---

contextualhelp/data.json

Added new faq in the ‘Payment’ section

[IOBP-1051] New FAQ added

---

definitions.yml
package.json
status/backend.json

This pull request includes updates to the `definitions.yml` and `package.json` files to add support for `de` language for `BackendStatusMessage` type

chore: [IOBP-1100] Add missing german definition

---

status/backend.json

chore: disable iPatente CTA in MDL credential details screen

---

contextualhelp/data.json

Added new method Satispay on PAYMENTS_HOME

Added new method Satispay on FAQ PAYMENTS_HOME

---

contextualhelp/data.json
status/backend.json

> [!Warning]
> This PR depens on https://github.com/pagopa/io-services-metadata/pull/933
> [!NOTE]
> The merge of this PR is scheduled for **February 7, 2025**
This PR replace all urls that refers to ioapp.it with account.ioapp.it
- Edit remote value for URLs
- Edit all values on `/contextualhelp/data.json`

[IOPID-2670] edit remote URL that refers to ioapp.it with account.ioapp.it

---

contextualhelp/data.json

Some changes to the Wallet FAQ
Route:
WALLET_HOME
ITW_PRESENTATION_CREDENTIAL_DETAIL
ITW_PRESENTATION_CREDENTIAL_ATTACHMENT

Update Wallet FAQ

---

status/backend.json

This PR disables the IDPay feature remotely.

chore: [IOBP-1180] Disable IDPay feature

---

definitions.yml
status/backend.json

This PR adds the FIMS configuration list.
- New property `services` added to the FIMS configuration in order to store known service details (for analytics tracking in App IO)
CI should succeed

chore: [IOCOM-2100] FIMS configuration list

---

definitions.yml
status/backend.json

updates for PN's banner in IO-App's landing screen
- addition of said serviceID to backend.json
- types update
CI should pass

[IOCOM-2206] addition of PN notification service ID to backend.json

---

status/backend.json

This PR disables the IDPay feature flag until it is released in production in the next weeks.

chore: Disable IDPay feature flag

---

definitions.yml
status/backend.json

This PR adds the new feature flag for IOMarkdown.
- A min_app_version flag that enables IOMarkdown from a version on
CI should succeed

feat: [IOAPPX-491] New feature flag for IOMarkdown

---

definitions.yml
status/backend.json

update to backend.json's payload
- updated backend.json
- types to reflect backend.json
tests should pass

[IOCOM-2275] SEND TOS+PrivacyURL

---

status/backend.json

addition of said entry to said array
see description
tests should pass

feat: [IOCOM-2277] SEND reminder banner in landing banners

---

contextualhelp/data.json

Made some changes and deleted some FAQ

[IOPID-2830] FAQ update

---

definitions.yml
status/backend.json

Reverts pagopa/io-services-metadata#953

Revert "chore: update cdc feature flag definition"

---

definitions.yml
package.json
status/backend.json

This PR adds the `webViewPaymentFlow` feature flag, which enables the payment flow inside the web view instead of the in-app browser.
- Added definitions with min app version to the new property `webViewPaymentFlow`
- Currently, the version is set to `5.0.0.0` because we don't want enable it, as soon as the development is completed, we will put the correct version there.

feat: [IOBP-1577] Add `webViewPaymentFlow` feature flag

---

contextualhelp/data.json

Resolve typo for `PAYMENT_CHECKOUT_MAKE` FAQ
- Resolved text typo
N/A

fix: text typo for `PAYMENT_CHECKOUT_MAKE`

---

assistanceTools/zendesk.json

Added a new subcategory for Zendesk service requests
-  added "Bonus elettrodomestici" under "Bonus e Iniziative" category
The impacted json is syntactically correct.

Feat: new subcategory bonus_elettrodomestici

---

status/backend.json

IOMarkdown 3.4.0.0+

---

status/backend.json

This PR sets the min app version for IOMarkdown to 3.5.0.0
- Feature A
- Feature B

IO Markdown 3.5.0.0

---

status/backend.json

TOS remote update to the last version 5.2
This PR depends on https://github.com/pagopa/io.italia.it/pull/591

TO Update to 5.2 version

---

status/backend.json

This PR enables the new app feedback feature on io-app

Activate App feedback system on qualtrics

---

contextualhelp/data.json

Update `PAYMENT_HOME` FAQ text
Ensure that FAQ are aligned with design requirements

chore: [IOBP-1626] Update `PAYMENT_HOME` FAQ

---

contextualhelp/data.json

Updated the Italian text and the German translations of the FAQs in PAYMENT_RECEIPT, adding that pagoPA receipts are also available when logged in.
- Feature A
- Feature B

Update text on FAQ PAYMENT_RECEIPT

---

status/backend.json

chore: disable IOMarkdown in beta

---

status/backend.json

chore: Enable IOMarkdown on beta

---

status/backend.json

This PR is updating `MyBank` banner title and description 
- Add missing translations
Ensure that text is aligned with [design](https://www.figma.com/design/KY9BpP4LaSSd18fuYMwxYK/Paga-un-avviso-pagoPA?node-id=13719-8265&t=ATbbyjW2QcQHypwc-0) requirements

chore: [IOBP-1652] Update `MyBank` banner translations

---

status/backend.json

This PR temporarily disables the WebView payment flow to be available only in certain hours for test purposes.

chore: Disable WebView payment flow

---

status/backend.json

This PR enables the webview payment flow on version `3.6.0.9`

chore: Enable webview payment flow on version `3.6.0.9`

---

status/backend.json

This PR enables the webview payment flow on version `3.6.0.9`

chore: Enable payment webview flow

---

definitions.yml
package.json
status/backend.json

This PR adds optional `loginUrl ` inside `loginConfig `.
- Added `loginUrl ` inside `loginConfig ` to `definitions.yml`
- Added `loginUrl ` inside `loginConfig `  to `backend.json` 
- Bump `package.json` version
- Run `yarn generate:all`
- Run `yarn run_checks`. Ensure no error is reported.
- All PR checks have to be green.

chore: [IOPID-3135] Add optional `loginUrl` to `loginConfig`

---

status/backend.json

This PR disables new markdown for current app release

Bumps ioMarkdown version for next release

---

status/backend.json

This PR disables the iOS webview payment flow.

chore: Disable WebView payment flow on iOS

---

status/backend.json

IOMarkdown enabled in production from 3.8.0.9

---

status/backend.json

This PR enables the payments maintenance status message banner

chore: [IOBP-1809] Enable payments maintenance banner

---

status/backend.json

This PR updates SEND AAR QRCode regex to support login.notifichedigitali.it domains
- SEND AAR QRCode updates
Check that the new following urls are matched when the regex is used in a javascript environment:
```
https://login.notifichedigitali.it/?aar=xyz123
https://dev.login.notifichedigitali.it/?aar=xyz123
https://test.login.notifichedigitali.it/?aar=xyz123
https://hotfix.login.notifichedigitali.it/?aar=xyz123
https://uat.login.notifichedigitali.it/?aar=xyz123
https://login.notifichedigitali.it/messaggi/notifiche?aar=xyz123
```

feat: [IOCOM-2517] Update SEND AAR QRCode regex

---

definitions.yml
package.json
status/backend.json

This PR adds the `show_cgn_categories_modal` remote FF
- Added `show_cgn_categories_modal` FF to `definitions.yml` and `backend.json` 
- Bump package version
All checks have to be green

chore: [IOBP-1926] Add `show_cgn_categories_modal` FF

---

status/backend.json

This PR removes the CGN-related maintenance banner

chore: Disable CGN maintenance banner

---

status/backend.json

> [!Warning] 
> This PR can be merged after 8 a.m on September 4th
Reverts pagopa/io-services-metadata#1019

Revert "chore: [IOPID-3364] add maintenance banner on landing and email verification screens "

---

status/backend.json

This PR restores the old FF version to ensure that the new app release does not include the feature when it goes live
- Set up ff version to `4.x`
N/A

chore: [IOBP-000] Restore IDPay Bonus ff

---

definitions.yml
status/backend.json

This PR Adds the send AAR delegate url
- Adds the send AAR delegate url
Automated tests should succeed

feat: [IOCOM-2554] Added Send AAR delegate url

---

assistanceTools/zendesk.json

Add "Carta della Cultura" in "Bonus e iniziative" for support request
- reordered subcategories in "Bonus e iniziative"
- added "Carta della Cultura"

Feat: Add "Carta della Cultura" in "Bonus e iniziative" for support request

---

status/backend.json

This PR is removing CdC assistance banners
- Removed CdC banners
N/A

chore: [IOBP-000] Removed CdC banners
