- services.yml
- services/5b3f4b1da9ab400f54dc5ab1c49a.json
This pr introduces the metadata for the service (id: 5B3F4B1DA9AB400F54DC5AB1C49A) provided by the Municipality of Valsamoggia to declare the service as local.
> Add metadata related to Municipality of Valsamoggia

- bonus/specs/bpd/pm/walletv2.json
This pr updates the `CreditCard` definition, in order to support the new field `productType` and identify a Privative card
> [#177186994] update CreditCard definition

- bonus/specs/bpd/pm/walletv2.json
This pr changes the PM specification in order to support the search of privative card.
> [#177142050] Add pancode to pm `/v1/cobadge/pans` specification

- status/cobadgeServices.json
new co-badge service provider  ( Intesa San Paolo ).
only 1 issuer abi (06225 - cassa di risparmio del Veneto) for testing in production.
> added ISP with only 1 issuer

- status/abi.json
- status/cobadgeServices.json
Poste Italia SpA co-badge service.
It retrieves Postamat cards.
A PostaMat card is not valid for e-commerce and use a Mastercard or Maestro circuit
> [BSP-62] add poste italiane co-badge service

- package.json
- src/checks/checkVisibleServicesWebView.ts
This PR add a check on `visible service webview data`
> Add a sanity check for visible services webview data

- contextualhelp/data.json
This PR updates the [Route name of the card detail screen](https://github.com/pagopa/io-app/pull/3064), in order to display the remote FAQ correctly.
> [IA-10] Update Route name

- definitions.yml
- status/backend.json
This PR add the `favourite_language` section to the `Section` type definition and corresponding backend section for manage the favourite language status bar in the app.
> [IA-97] Add type definition and backend section for manage favourite language status bar

- definitions.yml
This PR fix a bug introduced in #406.
The `favorite_language` field was inserted without the type definition in the `properties` field.
> [IA-149]Add favourite_language properties field

- status/backend.json
This PR removes the banner from Wallet page—since now almost all participants to Cashback program have received a message with further instructions
> [IA-178] Update backend.json

- contextualhelp/data.json
This pr moves the faq "Perchè il mio certificato ora risulta non più valido?" from `EUCOVIDCERT_MARKDOWN_DETAILS` to `EUCOVIDCERT_CERTIFICATE`.
> Move expired certificate faq to EUCOVIDCERT_CERTIFICATE

- definitions.yml
- status/backend.json
This PR add the type definition and the config (at the moment setted to off) for Zendesk.
The choice to use an object was made because it allows to extend it in the future.
> [ASZ-103] Add zendesk remote feature flag

- status/backend.json
This PR set Zendesk as assistanceTool so that the users can send assistance request in Zendesk.
> set zendesk as assistanceTool

- status/backend.json
This pr disables the EUCovidCertificate in app banner.
> Disable EUCovidCert warning

- definitions.yml
- package.json
- status/backend.json
This PR is going to add a `PremiumMessages` configuration object with a `opt_in_enabled` property used as a remote Feature Flag for the Premium Messages opt-in/out feature.
> [IA-768] Add a remote Feature Flag for the Premium Messages opt-in/out feature

- definitions.yml
- status/backend.json
This PR adds a dedicated config for BancomatPay
It includes 3 flags:
- `display` If true BPay can be showed in the wallet section
- `onboarding` If true BPay can be added in the user's wallet
- `payment` If true BPay can be used to pay
> [IA-791] Add BancomatPay config

- contextualhelp/data.json
I have:
- updated and added here all the FAQs of Wallet_Home, which were not remotized;
- added specific FAQs for each payment method, both in the onboarding method process and in the card detail of each method once this has been added;
- Deleted any reference to Cashback (also when it comes to methods such as BancomatPAY)
- Deleted a route that is no longer relevant(WALLET_PAYMENT_METHOD_DETAIL) and another one whose name was incorrect (WALLET_ONBOARDING_BANCOMAT_CHOOSE_BANK)
- Added an FAQ regarding the Back of Italy's financial education program ("Come posso saperne di più sui pagamenti digitali?")
- Added the same FAQs in the English version — all of which were not remotized up to now.
> [IA-669] Copy updates to the FAQs of the Wallet section

- definitions.yml
- package.json
- status/backend.json
This PR supports the remote configuration for a defined domain to use as the cookie domain for FIMS session token
> [IAFIMS-8] Supports domain specification for fims

- definitions.yml
- package.json
- status/backend.json
This PR is going to add a configuration for the IO app barcode scanner with the Poste Data Matrix.
The configuration object `BarcodesScannerConfig` has been made "abstract" because in the future we could address other types of barcodes for different organizations.
⚠️ This PR is going to increase the version number too in order to instantly create the new tag.
> [IA-843] Add a remote Feature Flag for the Poste Data Matrix

- definitions.yml
- package.json
- status/backend.json
This PR adds the `cdc` section in the section status.
Please, remember when you merge the PR to create the tag with the new version `1.0.14`
> [AP-31] Add cdc section status

- status/backend.json
This PR is going to enable the Poste Data Matrix feature flag in order to start testing in the internal beta release.
> Enable the `dataMatrixPosteEnabled` remote feature flag

- status/backend.json
This PR is going to enable the `opt_in_out_enabled` feature flag related to the "Spunta Blu".
> Enable the premium messages opt-out feature flag

- definitions.yml
- package.json
- status/backend.json
This PR is going to add a remote configuration for the PN feature. The configuration will be used for:
- enabling/disabling the feature
- configuring the URL that will be open when the user wants to check the complete status history of a notification
> [IAMVL-91] Add a remote configuration for the PN feature

- definitions.yml
- package.json
- status/backend.json
The logic to filter psps by origin is changed so this PR changes the name of in the config to have a better meaning.
> Change from allowedPspsByOrigin to preferredPspsByOrigin

- status/backend.json
This PR sets PayPal services under maintenance:
1. Enables the Feature Flag to disable PayPal method
2. Enables the banner in the Wallet page
> Paytipper (PayPal) Scheduled Maintenance

- status/backend.json
This PR:
- disables the FF for PayPal
- enables the banner in Wallet page
The scheduled maintenance will start on 9/11/2022 at 9pm. 
More info: https://status.pagopa.gov.it/incidents/clcplg6s9gxb
> [IOAPPFD0-13] Scheduled Maintenance (Paytipper)

- status/backend.json
This PR enables a warning banner in wallet section, informing users about the schedule maintenance.
More info here: https://status.pagopa.gov.it/incidents/z6mn93mpvyyd
**To be merged at the beginning of the scheduled maintenance**
> Activate Banner in Wallet

- definitions.yml
- package.json
- status/backend.json
This PR fix the spec of `Firma con IO` reintroducing the `enabled` prop
> fix: Update FCI config  reintroducing enabled prop to support old app version

- definitions.yml
- package.json
- status/backend.json
This PR introduces the feature flag for the IDPay features with the properties `enabled` and the recently introduced `min_app_version`, allowing the activation by version and by platform.
The feature flag is:
```yaml
IdPayConfig:
type: object
description: "A configuration for the IdPay feature"
required:
- min_app_version
properties:
min_app_version:
$ref: "#/definitions/VersionPerPlatform"
description: "If min app version supported, the test user can onboard, configure and monitor an IdPay initiative"
```
> chore(IDPay): [IODPAY-90] Add `IdPayConfig` feature flag

- status/versionInfo.json
This PR sets the `min_app_version` to 2.35.0.1 in order to make sure that any PN message displays the precondition bottom sheet before opening
It also sets the `latest_released_app_version` to the common released one for consistency
> [IOCOM-PN] Min app version to 2.35.0.1 for PN message preconditions

- definitions.yml
- package.json
- status/backend.json
This PR adds the PN OptIn Service Id that allows the IO App to properly identify a PN message as the opt-in one
> [IOCOM-270] Added PN Opt In Service ID

- assistanceTools/zendesk.json
REASON: For Zendesk ticket submission in app IO: We need to enable the sub-category "Messaggi" ---> "Ho un problema con un messaggio di SEND"
> feat: add SEND subcat for Messages tickets

- azure-pipelines.yml
Fix an issue where pipeline failed to copy data to storage account due to invalid characters as arguments
> fix: Escape characters in azure devops pipeline

- status/backend.json
This PR bumps `min_app_version` for `emailUniquenessValidation`, `fastLogin` and `opt_in` to `2.51.0.0`.
> [IOPID-1307] - Bump `min_app_version` for `emailUniquenessValidation`, `fastLogin` and `opt_in`

- status/versionInfo.json
This PR bumps the **mandatory** `min_app_version` from `2.43.0.3` to `2.50.0.5`
> [IOPID-1337] Bump `min_app_version` from `2.43.0.3` to `2.50.0.5` 

- assistanceTools/zendesk.json
feat: Add Bonus PC subcategory to Zendesk
Add Bonus PC subcategory under Bonus and Initiatives category. This is needed to open a new support request from app IO.
> feat: Add Bonus PC subcategory to Zendesk

- definitions.yml
- package.json
- status/backend.json
This PR adds definitions and an initial implementation of the alert (formally called a banner) service to be displayed on the home payments page.
In this PR @thisisjp will insert the texts to be shown for this banner.
- Added definitions
- Upgraded package version
- Added a scaffolding structure for the payments banner section
> chore: [IOBP-696] Add payments section banner definitions

- status/backend.json
This PR enables a disclaimer banner in the new payment page
> Enable banner on new payments page

- definitions.yml
addition of said optional flag in `definitions.yml`, after it has been added to backendStatus in a previous PR
- addition of said flag
tests should solve correctly
> `fims.historyEnabled` flag in definitions.yml

- status/backend.json
This PR enable the new wallet section feature flag for the app version `2.64.0.1`
> chore: enable new wallet section for 2.64.0.1 app version

- status/backend.json
This PR sets the min app version to the new payment section feature flag to `3.0.0.0` in order to disable it.
> chore: disable new wallet section payment feature flag

- status/backend.json
> [!WARNING]
> This PR depends on: https://github.com/pagopa/io.italia.it/pull/535
- Users with v <2.65.0.0 will see a banner in Wallet page engaging them to update the app to the latest version, with a new dedicated URL
- Users with v >= 2.65.0.0 will see a banner in Payments page to explain how to pay with card or PayPal, with a new dedicated URL
> Update payments banners

- contextualhelp/data.json
This PR fixes a typo in the FAQ json file (`PAYMENT_HOME` instead of the correct one `PAYMENTS_HOME`)
> Fix wrong route in FAQ

- status/backend.json
This PR slightly changes the banner visibile in payments section:
- removed references to PayPal
- changed level from normal to warning, to boost users engagement
> Modify payments banner

- definitions.yml
- package.json
- status/backend.json
This PR adds a remote feature flag to the sessionRefresh feature. If this new remote FF is enabled, after at least 2 minutes of app background, when the app back in foreground, the token will be automatically refreshed 
- Add the `sessionRefresh` attribute to the backend.json 
- Added the model definitions from the open API specs (into the fastLogin object);
- Upgraded the package.json version (align version in package.json with released version)
> [IOPID-2049] Add remote FF of sessionRefresh after two minutes in background 

- definitions.yml
- status/backend.json
This PR fixes the `min_app_version` for FIMS in order to use IO-App helpers functions.
- `min_app_version` promoted to top level property in `fims` configuration
Static checks should succeed.
> [IOCOM-1649] Proper structure for FIMS `min_app_version`

- definitions.yml
- status/backend.json
This PR removes the `min_app_version` from FIMS history, so only the main `min_app_version` under `fims` will be used.
- `min_app_version`and FIMS `history` removed
Static checks should succeed.
> [IOCOM-1680] Remove `min_app_version` from FIMS history

- status/backend.json
This PR bumps ToS version from `4.9` a `4.91`.
> chore: bump ToS version from `4.9` a `4.91`

- assistanceTools/zendesk.json
Add a new category "Documenti su IO" and 6 sub-categories.
- Add a new category "Documenti su IO" and 6 sub-categories. Note that English and German labels will be provided later by Product & Design team.
In app IO you need to click on '?' and create a new service request. Select "Documenti su IO" and one of its sub-categories.
> feat: add new categories for Documenti su IO

- definitions.yml
This pull request includes a small change to the `definitions.yml` file. The change adds support for the German language (`de-DE`) in the `definitions` section for FAQ
> fix: [IOBP-961] Add missing german key for FAQ

- contextualhelp/data.json
The first FAQ text for the PAYMENT_METHOD_DETAILS_SCREEN route has been fixed.
> [IOBP-1034] Fixed FAQ in payment methods

- status/versionInfo.json
This PR bumps the `min_app_version` from `2.68.0.0` to `2.77.0.3`
> [SIW–1877] Bump `min_app_version` from `2.68.0.0` to `2.77.0.3`

- contextualhelp/data.json
added the right content to a login-related FAQ (thanks to @dhinterlechner who reported the bug). This resolves #891
> Wrong FAQ answer in AUTHENTICATION_OPT_IN

- status/backend.json
This PR enables the feedback banner showed when the user completes a payment, adding the qualtrics survey link.
- Added the min version to show this banner;
- Added the qualtrics survey link to the CTA of the banner;
> chore: [IOBP-996] Enable qualtrics payment feedback banner

- status/versionInfo.json
> [!NOTE]
> The merge of this PR is scheduled for **18th December 2024**
This PR bumps the min app version required to run the IO App. 
- Bumped `min_app_version` from `2.77.0.3` to `2.78.0.11` 
> [SIW-1922] Bump `min_app_version` from `2.77.0.3` to `2.78.0.11`

- definitions.yml
- package.json
- status/backend.json
This PR adds the remote FF for the iPatente CTA inside the MDL details screen
- Added **required** `ipatente_cta_visible` property in the `ItwConfig`
- Add `ipatente_cta_visible: true` in `status/backend.json`
- Bumped version to `1.0.52`
> [SIW-1919] Add iPatente MDL details screen CTA feature flag

- .github/workflows/publish_cdn.yml
As suggested by @Krusty93, in this PR I update the value of the sha in the workflow file that allows the deployment of the CDN
> Update the sha value in workflow in order to publish cdn

- .github/workflows/publish_cdn.yml
> [!Warning] 
> This PR is a fix of this PR https://github.com/pagopa/io-services-metadata/pull/917
As suggested by @Krusty93, in this PR I update the value of the sha in the workflow file that allows the deployment of the CDN.
> fix: Update the sha value in workflow in order to publish cdn

- definitions.yml
- package.json
- status/backend.json
This PR creates the `ipatente_cta` object to handle the visibility and tracking details of the iPatente service.
- Deleted `ipatente_cta_visible` property in ItwConfig
- Added the `ipatente_cta` object and added to `status/backend.json `
- Bumped version to `1.0.56`
> [SIW-1953] Add iPatente CTA property in ItwConfig

- .github/workflows/publish_cdn.yml
In order to deploy the CDN and not receive the error you see in [these deployment attempts](https://github.com/pagopa/io-services-metadata/actions/runs/12785222306), this command line was added to the deploy configuration file
> fix: Add workaround to deploy cdn

- .github/workflows/publish_cdn.yml
This PR is a fix of this PR https://github.com/pagopa/io-services-metadata/pull/920 and change the version of azcopy
> fix: change azcopy version

- .github/workflows/publish_cdn.yml
In order to resolve the problems on publish in this PR, as suggested by @Krusty93, I have updated the version of azcopy from 10.24.0 to 10.27.0
> change azcopy version from 10.24.0 to 10.27.0

- status/backend.json
This PR enables a warning banner with a text about a **short** maintenance on the CGN screens: `CGN_CATEGORIES` and `CGN_MERCHANTS_ALL`
- Added a status message of warning level to the routes `CGN_CATEGORIES` and `CGN_MERCHANTS_ALL`..
> [PE-863] Enable CGN short maintenance banner warning

- status/backend.json
This PR removes the CGN status banner showed inside the `CGN_CATEGORIES` screen
- Removed the items inside the status message array.
> chore: [PE-863] Removed CGN status banner

- definitions.yml
- status/backend.json
This PR adds an optional flag to disable the use of IOMarkdown in message and service details
- optional ioMarkdown section with optional proprerty
CI should succeed
> [IOCOM-2071] Flag for disabling IOMarkdown remotely

- status/versionInfo.json
> [!NOTE]
> The merge of this PR is scheduled for **February 7, 2025**
This PR bumps the min app version required to run the IO App. 
- Bumped `min_app_version` from `2.78.0.11` to `2.81.0.8`
> [IOPID-2684] Bump `min_app_version` from `2.78.0.11` to `2.81.0.8`

- status/backend.json
This PR changes the `landing_banners` priority order and remove the `SETTINGS_DISCOVERY` identifier
> [IOPID-2756] Change Banners priority order

- .github/workflows/static-checks.yml
This PR updates the `actions/cache` from version `v3.3.1` (deprecated) to `v4.2.0`
> ci: [IOAPPX-483] Update `actions/cache` due to GitHub deprecation

- status/backend.json
This PR enables IOMarkdown for IO-App versions 3.1.0.0+
- min_app_version set to 3.1.0.0
CI should succeed.
> chore: IOMarkdown enabled on 3.1.0.0+

- status/backend.json
This PR sets 3.2.0.0 as the min app version for IOMarkdown
> chore: min app version 3.2.0.0 for IOMarkdown

- status/backend.json
This PR disables IOMarkdown (messages/services) for IO App versions lower than 3.3.0.0
> chore: enables IOMarkdown from 3.3.0.0

- definitions.yml
- package.json
- status/backend.json
This PR adds the `pspBanner` props and definitions. The goal of this remote configuration is to show/hide a banner inside the PSP selection screen based on the payment method selected by the user.
- Defined the `pspBanner` with a key-value object where the keys are the payment method short name and the values are Banner object type to show/hide a banner;
> feat: [IOBP-1562] Add `pspBanner` property and definitions

- definitions.yml
- package.json
- status/backend.json
This pull request introduces a new configuration for CDC called `cdcV2` since we cannot edit `cdc` property without causing IO app crash
- `cdcV2` reference under `definitions` and defined the `CdcConfigV2` object with its properties.
- Added the `cdcV2` configuration with the `min_app_version` property for both iOS and Android platforms.
N/A
> chore: [IOBP-1419] Cdc min app version feature flag

- status/backend.json
This PR enabled IOMarkdown in production, starting from IOApp version 3.1.0.0.
- Feature A
- Feature B
> chore: enable IOMarkdown from 3.1.0.0

- status/backend.json
This PR enables the webview payment flow from the version `3.6.0.1` that is currently in Beta
- Set the version to the `webViewPaymentFlow` attribute to the value `3.6.0.1`;
- Open the app IO with version `3.6.0.1` in Beta and check that the flow is started within a webview instead of the in-app browser when you start a new payment.
> chore: Enable `webViewPaymentFlow` from the v. `3.6.0.1`

- status/backend.json
This PR enables the webview payment flow on version `3.6.0.9` both on iOS and Android
> chore: Enable payment webview flow

- definitions.yml
- status/backend.json
This PR adds a (javascript-like) regex that matches AAR QRCode (SEND), for every known environment.
- Matched urls are in case-insensitive format 
`https://[dev.|test.|hotfix.|uat.|]cittadini.notifichedigitali.it/[paths/]?aar=anyValue`
with any leading and/or trailing spaces
Check that the following urls are matched when the regex is used in a javascript environment:
```
https://dev.cittadini.notifichedigitali.it/?aar=xyz123
https://test.cittadini.notifichedigitali.it/?aar=xyz123
https://hotfix.cittadini.notifichedigitali.it/?aar=xyz123
https://uat.cittadini.notifichedigitali.it/?aar=xyz123
https://cittadini.notifichedigitali.it/?aar=xyz123
https://cittadini.notifichedigitali.it/notifications/detail?aar=xyz123
https://dev.cittadini.notifichedigitali.it/some/path?aar=xyz123        // This …
```
> feat: [IOCOM-2458] SEND AAR QRcode Regex

- definitions.yml
- package.json
This PR adds to the `definitions.yml` a new `label_cta` field to the `StatusMessage` definition, allowing it to be set remotely.
- Added `label_cta` property to the `StatusMessage` definition.
> chore: [IOBP-1874] Add banner status message `label_cta` property

- status/backend.json
This PR enables a warning banner with a text about a **short** maintenance on the CGN screens: `CGN_MERCHANTS_CATEGORIES` and `CGN_MERCHANTS_LIST_BY_CATEGORY`
- Added a status message of warning level to the routes `CGN_MERCHANTS_CATEGORIES` and `CGN_MERCHANTS_LIST_BY_CATEGORY`..
> chore: [IOBP-1930] Enable CGN status banner short maintenance

- status/backend.json
update of said regEx
updated said regex to only match "uat" and production URLs, and moved the "uat" subdmain from first to second place, as per specifications.
automated tests should pass, also test the given regex on any JS engine (such as the browser's console) like this:
```
const a = new RegExp(aarQRCodeRegexString, "i")),
const result = a.test(data)
```
and with those strings:
```
---- passing cases ---------
"https://cittadini.notifichedigitali.it/io?aar=test" 
https://cittadini.uat.notifichedigitali.it/io?aar=test" 
"https://login.notifichedigitali.it/io?aar=test"
"https:/login.uat.notifichedigitali.it/io?aar=test" 
"             https://cittadini.notifichedigitali.it/io?aar=test" 
"             https://cittadini.notifichedigitali.it/io?aar=test            " …
```
> [IOCOM-2575] SEND AAR QR CODE regex update

- definitions.yml
- status/backend.json
This PR removes all the occurrences related to the `cie_id` FF from the `definitions.yml` and from the `backend.json` files
It can be tested from the following PRs:
- https://github.com/pagopa/io-dev-api-server/pull/537
- https://github.com/pagopa/io-app/pull/7357
> refactor: [IOPID-2649] Remove cieid ff occurrences from `definitions.yml` and form `backend.json`
